controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - base_forearm_joint
      - forearm_0_1_joint
      - forearm_arm_joint
      - arm_0_1_joint
      - arm_gripper_joint