# controller_list:
#   - name: arm
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - wam/base_yaw_joint
#       - wam/shoulder_pitch_joint
#       - wam/shoulder_yaw_joint
#       - wam/elbow_pitch_joint
#       - wam/wrist_yaw_joint
#       - wam/wrist_pitch_joint
#       - wam/palm_yaw_joint
controller_list:
  - name: arm
    # action_ns: follow_joint_trajectory
    # https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/55
    action_ns: scaled_pos_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    # default: true
    # joints: [wam/base_yaw_joint, wam/shoulder_pitch_joint, wam/shoulder_yaw_joint, wam/elbow_pitch_joint, wam/wrist_yaw_joint, wam/wrist_pitch_joint, wam/palm_yaw_joint]
    joints: [base_yaw_joint, shoulder_pitch_joint, shoulder_yaw_joint, elbow_pitch_joint, wrist_yaw_joint, wrist_pitch_joint, palm_yaw_joint]
    # - name: hand
    #   action_ns: follow_joint_trajectory
    #   type: FollowJointTrajectory
    #   # type: JointTrajectoryController
    #   default: true
    #   joints:
    #     - wam/bhand/finger_1/prox_joint
    #     - wam/bhand/finger_1/med_joint
    #     - wam/bhand/finger_1/dist_joint
    #     - wam/bhand/finger_2/prox_joint
    #     - wam/bhand/finger_2/med_joint
    #     - wam/bhand/finger_2/dist_joint
    #     - wam/bhand/finger_3/med_joint
    #     - wam/bhand/finger_3/dist_joint