# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: warm
  joint_model_group_pose: upright
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - wam/base_yaw_joint
    - wam/shoulder_pitch_joint
    - wam/shoulder_yaw_joint
    - wam/elbow_pitch_joint
    - wam/wrist_yaw_joint
    - wam/wrist_pitch_joint
    - wam/palm_yaw_joint
    - wam/bhand/finger_1/prox_joint
    - wam/bhand/finger_1/med_joint
    - wam/bhand/finger_1/dist_joint
    - wam/bhand/finger_2/prox_joint
    - wam/bhand/finger_2/med_joint
    - wam/bhand/finger_2/dist_joint
    - wam/bhand/finger_3/med_joint
    - wam/bhand/finger_3/dist_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# added (begin)
wam_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint
  gains:
      # panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
      # panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
      # panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
      # panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
      # panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
      # panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
      # panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }
      wam/base_yaw_joint: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
      wam/shoulder_pitch_joint: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
      wam/shoulder_yaw_joint: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
      wam/elbow_pitch_joint: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
      wam/wrist_yaw_joint: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
      wam/wrist_pitch_joint: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
      wam/palm_yaw_joint: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

  constraints:
      goal_time: 2.0
  state_publish_rate: 25

wam_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - wam/bhand/finger_1/prox_joint
      - wam/bhand/finger_1/med_joint
      - wam/bhand/finger_1/dist_joint
      - wam/bhand/finger_2/prox_joint
      - wam/bhand/finger_2/med_joint
      - wam/bhand/finger_2/dist_joint
      - wam/bhand/finger_3/med_joint
      - wam/bhand/finger_3/dist_joint

  gains:
      # panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
      # panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_1/prox_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_1/med_joint: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_1/dist_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
      # 
      wam/bhand/finger_2/prox_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_2/med_joint: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_2/dist_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
      # 
      wam/bhand/finger_3/med_joint: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
      wam/bhand/finger_3/dist_joint: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

  state_publish_rate: 25

# (end)
controller_list:
  # []
  # added2 (begin)
  - name: wam_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    # type: JointTrajectoryController
    default: true
    joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint
  - name: wam_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    # type: JointTrajectoryController
    default: true
    joints:
      - wam/bhand/finger_1/prox_joint
      - wam/bhand/finger_1/med_joint
      - wam/bhand/finger_1/dist_joint
      - wam/bhand/finger_2/prox_joint
      - wam/bhand/finger_2/med_joint
      - wam/bhand/finger_2/dist_joint
      - wam/bhand/finger_3/med_joint
      - wam/bhand/finger_3/dist_joint
  # - name: /vel_based_pos_traj_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   # type: JointTrajectoryController
  #   default: true
  #   joints:
  #     - wam/base_yaw_joint
  #     - wam/shoulder_pitch_joint
  #     - wam/shoulder_yaw_joint
  #     - wam/elbow_pitch_joint
  #     - wam/wrist_yaw_joint
  #     - wam/wrist_pitch_joint
  #     - wam/palm_yaw_joint
  #     - wam/bhand/finger_1/prox_joint
  #     - wam/bhand/finger_1/med_joint
  #     - wam/bhand/finger_1/dist_joint
  #     - wam/bhand/finger_2/prox_joint
  #     - wam/bhand/finger_2/med_joint
  #     - wam/bhand/finger_2/dist_joint
  #     - wam/bhand/finger_3/med_joint
  #     - wam/bhand/finger_3/dist_joint
  # (end)
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    []
  gains:
    {}
hand_position_controller:
  type: position_controllers/JointPositionController
  joints:
    []
  gains:
    {}

#added
#arm_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#      - wam/base_yaw_joint
#      - wam/shoulder_pitch_joint
#      - wam/shoulder_yaw_joint
#      - wam/elbow_pitch_joint
#      - wam/wrist_yaw_joint
#      - wam/wrist_pitch_joint
#      - wam/palm_yaw_joint
#      
#      - wam/bhand/finger_1/prox_joint
#      - wam/bhand/finger_1/med_joint
#      - wam/bhand/finger_1/dist_joint
#      - wam/bhand/finger_2/prox_joint
#      - wam/bhand/finger_2/med_joint
#      - wam/bhand/finger_2/dist_joint
#      - wam/bhand/finger_3/med_joint
#      - wam/bhand/finger_3/dist_joint
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#     stop_trajectory_duration: 0.5
#     state_publish_rate: 25
#     action_monitor_rate: 10
#joint_group_position_controller:
#  type: position_controllers/JointGroupPositionController
#  joints:
#    - wam/base_yaw_joint
#    - wam/shoulder_pitch_joint
#    - wam/shoulder_yaw_joint
#    - wam/elbow_pitch_joint
#    - wam/wrist_yaw_joint
#    - wam/wrist_pitch_joint
#    - wam/palm_yaw_joint
#      
#    - wam/bhand/finger_1/prox_joint
#    - wam/bhand/finger_1/med_joint
#    - wam/bhand/finger_1/dist_joint
#    - wam/bhand/finger_2/prox_joint
#    - wam/bhand/finger_2/med_joint
#    - wam/bhand/finger_2/dist_joint
#    - wam/bhand/finger_3/med_joint
#    - wam/bhand/finger_3/dist_joint
#initial:  # Define initial robot poses.
#  - group: warm
#    pose: upright
#  - group: bhand
#    pose: open_def
